apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: controlplane.cluster.x-k8s.io
spec:
  latestResourceSchemas:
  - v250508-284c602.gardenershootcontrolplanes.controlplane.cluster.x-k8s.io
  - v250508-284c602.gardenershootclusters.infrastructure.cluster.x-k8s.io
  - v250508-284c602.gardenerworkerpools.infrastructure.cluster.x-k8s.io
  # CAPI resources for mock controller
  - v250508-9fbc50a43.clusters.cluster.x-k8s.io
  - v250508-9fbc50a43.machinepools.cluster.x-k8s.io
  permissionClaims:
    - group: ""
      resource: "secrets"
      all: true