apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: controlplane.cluster.x-k8s.io
spec:
  latestResourceSchemas:
    - generated.gardenershootcontrolplanes.controlplane.cluster.x-k8s.io
    - generated.gardenerworkerpools.infrastructure.cluster.x-k8s.io
    - generated.gardenershootclusters.infrastructure.cluster.x-k8s.io
    # CAPI resources for mock controller
    - generated.clusters.cluster.x-k8s.io
    - generated.machinepools.cluster.x-k8s.io
  permissionClaims:
    - group: ""
      resource: "secrets"
      all: true
