//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/gardener/gardener/pkg/apis/core/v1beta1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerShootControlPlane) DeepCopyInto(out *GardenerShootControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerShootControlPlane.
func (in *GardenerShootControlPlane) DeepCopy() *GardenerShootControlPlane {
	if in == nil {
		return nil
	}
	out := new(GardenerShootControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GardenerShootControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerShootControlPlaneList) DeepCopyInto(out *GardenerShootControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GardenerShootControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerShootControlPlaneList.
func (in *GardenerShootControlPlaneList) DeepCopy() *GardenerShootControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(GardenerShootControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GardenerShootControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerShootControlPlaneSpec) DeepCopyInto(out *GardenerShootControlPlaneSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(v1beta1.Addons)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudProfileName != nil {
		in, out := &in.CloudProfileName, &out.CloudProfileName
		*out = new(string)
		**out = **in
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(v1beta1.DNS)
		(*in).DeepCopyInto(*out)
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]v1beta1.Extension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(v1beta1.Networking)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(v1beta1.Monitoring)
		(*in).DeepCopyInto(*out)
	}
	in.Provider.DeepCopyInto(&out.Provider)
	if in.Purpose != nil {
		in, out := &in.Purpose, &out.Purpose
		*out = new(v1beta1.ShootPurpose)
		**out = **in
	}
	if in.SecretBindingName != nil {
		in, out := &in.SecretBindingName, &out.SecretBindingName
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]v1beta1.NamedResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1beta1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExposureClassName != nil {
		in, out := &in.ExposureClassName, &out.ExposureClassName
		*out = new(string)
		**out = **in
	}
	if in.SystemComponents != nil {
		in, out := &in.SystemComponents, &out.SystemComponents
		*out = new(v1beta1.SystemComponents)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(v1beta1.ControlPlane)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulerName != nil {
		in, out := &in.SchedulerName, &out.SchedulerName
		*out = new(string)
		**out = **in
	}
	if in.CloudProfile != nil {
		in, out := &in.CloudProfile, &out.CloudProfile
		*out = new(v1beta1.CloudProfileReference)
		**out = **in
	}
	if in.CredentialsBindingName != nil {
		in, out := &in.CredentialsBindingName, &out.CredentialsBindingName
		*out = new(string)
		**out = **in
	}
	if in.AccessRestrictions != nil {
		in, out := &in.AccessRestrictions, &out.AccessRestrictions
		*out = make([]v1beta1.AccessRestrictionWithOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerShootControlPlaneSpec.
func (in *GardenerShootControlPlaneSpec) DeepCopy() *GardenerShootControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(GardenerShootControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenerShootControlPlaneStatus) DeepCopyInto(out *GardenerShootControlPlaneStatus) {
	*out = *in
	in.ShootStatus.DeepCopyInto(&out.ShootStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenerShootControlPlaneStatus.
func (in *GardenerShootControlPlaneStatus) DeepCopy() *GardenerShootControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(GardenerShootControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderGSCP) DeepCopyInto(out *ProviderGSCP) {
	*out = *in
	if in.ControlPlaneConfig != nil {
		in, out := &in.ControlPlaneConfig, &out.ControlPlaneConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.InfrastructureConfig != nil {
		in, out := &in.InfrastructureConfig, &out.InfrastructureConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkersSettings != nil {
		in, out := &in.WorkersSettings, &out.WorkersSettings
		*out = new(v1beta1.WorkersSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderGSCP.
func (in *ProviderGSCP) DeepCopy() *ProviderGSCP {
	if in == nil {
		return nil
	}
	out := new(ProviderGSCP)
	in.DeepCopyInto(out)
	return out
}
