name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
    permissions:
      contents: read

  oci-images:
    name: Build OCI-Images
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@master
    with:
      name: cluster-api-provider-gardener
      version: ${{ needs.prepare.outputs.version }}
      oci-repository: gardener/cluster-api-provider-gardener
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-platforms: linux/amd64,linux/arm64
      target: cluster-api-provider-gardener
      ocm-labels:
      extra-tags: latest

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - uses: gardener/cc-utils/.github/actions/setup-git-identity@master
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: run-verify
        shell: bash
        run: |
          set -euo pipefail
          make verify

  sast-lint:
    uses: gardener/cc-utils/.github/workflows/sastlint-ocm.yaml@master
    permissions:
      contents: read
    with:
      linter: gosec
      run: |
        git config --global user.email some.one@some.where
        git config --global user.name 'Some One'
        make sast-report
